version: '3.8'

services:
  xaosao-chat-frontend:
    container_name: xaosao-chat-frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - xaosao-share-network
    ports:
      - "5174:5174"
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always
networks:
  xaosao-share-network:
    external: true